-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H'), COUNT(DATETIME) FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= '09' AND DATE_FORMAT(DATETIME, '%H') < 20
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H');